### ISSUE TITLE
Input K

### ISSUE THREAD

**Issue by j-faria** [adrn/TwoBody#12]
Hi Adrian,

Is there currently a way to input the semi-amplitude K in a `KeplerOrbit`?  
Sorry if I missed it in the code.

Thanks!

**Comment by adrn** [comment]
Currently no, but I agree that would be useful! Would it be sufficient for you to add `K` as an optional argument to the initializer?

**Comment by j-faria** [comment]
Yes, that would do. We could supply either `K` or `a`, but not both.
I also noticed that, when `a` is not provided, the `K` property of a `KeplerOrbit` instance, gets a value with units `1/d`. Is that supposed to happen?

**Comment by adrn** [comment]
I just added the option and pushed to master, so it is in the dev version. I'll do another release today so the pip-installable version also contains the new feature.

**Comment by adrn** [comment]
Oh, and on your second point, yes that is "expected" but a bit confusing: without a semi-major axis, `K` can't be computed from the elements. Perhaps doing `orbit.K` for those situations should throw an error instead...
